<div class="aboutMe">
        <div class="aboutMe-header">O mnie<span>.</span></div>
        <div class="aboutMe-part">Jestem Oskar Dąbrowski, mam obecnie 23 lata i pochodzę z małego miasta około 50 kam od Torunia. Obecnie studiuję Geoinformację na Uniwersytecie Mikołaja Kopernika. Moje zainteresowanie programowaniem narodziło się w połowie drugiego roku licencjatu od grafiki wektorowej. Moje zainteresowanie rosło podczas tworzenia grafik i poznawania podstaw języka SVG. Z czasem zainteresowałem się programowaniem jako czymś więcej niż dodatek do tworzenia grafiki. Zacząłem od programowania w języku Python który obecnie również mam na studiach. Poznałem jego podstawy, jednakże brakowało mi elementu grafiki komputerowej co przyczyniło się do większego zainteresowania programowaniem Front-End. Pierwotnie czytałem książki i przechodziłem kursy freeCodeCamp, aby potem przenieść się na platformę Udemy na której łącznie przerobiłem około 200 godzin kursów (nie licząc pracy własnej) co doprowadziło mnie do obecnego poziomu.
        </div>
        <div class="aboutMe-headerSmall">Doświadczenie zawodowe<span>.</span></div>
        <div class="aboutMe-part">Jako student szukałem staży w zawodzie powiązanym z moim kierunkiem studiów. Zatem odbywałem praktyki w urzędzie, gdzie początkowo przydzielono mnie do działu zarządzania gruntami a następnie do powiatowego ośrodka geodezyjnego. Następnie jako Asystent Geodety, gdzie uczyłem się obsługi sprzętu geodezyjnego oraz podstaw obsługi programów do kartowania. Wcześniej uczestniczyłem również w szkoleniu wojskowym programu Legia Akademicka jako druga tura po uruchomieniu programu.
        </div>
        <div class="aboutMe-headerSmall">Moje pasje<span>.</span></div>
        <div class="aboutMe-part">
        Jestem człowiekiem kreatywnym, lubię przede wszystkim tworzyć. Co przełożyło się na zainteresowanie grafiką komputerową i kartografią, dzięki temu szybko uczę się programów, bez problemu wychwytuje podobieństwa i poszukuję zamienników i odpowiedników w zależności od potrzeby. Obecnie jestem właścicielem Affinity Suite, zestawu programów do grafiki komputerowej angielskiej firmy Serif. Zainteresowałem się nimi nie tylko przez wzgląd na cenę, ale również przyjazny interfejs graficzny i fakt, iż programy łączą najlepsze cechy oprogramowania konkurencji. Oprogramowanie te wykorzystuję również do budowy stron np. poprzez grafikę SVG. Obecnie najwięcej czasu poświęcam programowaniu, w którym staram się rozwijać i poszerzać swoje horyzonty. Z dumą mogę stwierdzić, że obecnie piszę w pełni świadomy kod i z ciekawością spoglądam na projekty innych, z których wyciągam wnioski oraz się uczę.
        </div>
        <div class="aboutMe-headerSmall headerPhone">Serdecznie <span style="margin: 0rem 1rem;"> dziękuję </span> za poświęcony czas</div>
    </div>